name: Testes de Python

on:
  push:
    branches: [ "testes-unitarios" ]
  pull_request:
    branches: [ "testes-unitarios" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Executar testes
        run: |
          pytest

      - name: Executar testes com cobertura
        run: |
          pytest --cov=.
